fix: select infantry and vehicles fix
Adeptus-Dominus/ChapterMaster pull request #132
Opened 2023-10-08 16:41 UTC by felipeStouvenel

# Fix:
- Select all Infantry button fix (when 1 infantry is selected)
- Select all Vehicles button fix
- Error in a merge from another PR (caused some issues in the selection buttons)
- Fixed logs showing "Could not find vehicle with role {role}" when selecting infantry instead of vehicles, which caused slow downs in game
- Re did logic to select all (works planet side, when 1 unit is selected)

2023-10-08 18:34 UTC, OH296 reviewed
few minor points but mostly optional

2023-10-08 18:34 UTC, OH296 commented on objects/obj_controller/Mouse_50.gml
> +        if (mouse_x>=xx+1281) and (mouse_y>=yy+607) and (mouse_x<xx+1409) and (mouse_y<yy+636) and (cooldown<=0)
point _in_rectangle(mouse_x, mouse_y, x, y, xx, yy) is less complex

2023-10-08 18:34 UTC, OH296 commented on scripts/scr_company_view/scr_company_view.gml
>  	for (var v = 1; v <= 499; v++){
```suggestion
        var company_length = array_length(obj_ini.name[company])
	for (var v = 1; v <= company_length; v++){
```

2023-10-08 18:34 UTC, OH296 commented on objects/obj_controller/Mouse_50.gml
> +        if (mouse_x>=xx+1281) and (mouse_y>=yy+607) and (mouse_x<xx+1409) and (mouse_y<yy+636) and (cooldown<=0)
```suggestion
       if ( point _in_rectangle(mouse_x, mouse_y, xx+1281, yy+607, xx+1409, yy+636)) and (cooldown<=0)
```

2023-10-08 18:34 UTC, OH296 commented on objects/obj_controller/Mouse_50.gml
> +        if (mouse_x>=xx+1281) and (mouse_y>=yy+607) and (mouse_x<xx+1409) and (mouse_y<yy+636) and (cooldown<=0)
```suggestion
         if (point _in_rectangle(mouse_x, mouse_y, xx+1281, yy+607, xx+1409, yy+636)) and (cooldown<=0) 
```

2023-10-08 18:34 UTC, OH296 commented on scripts/scr_company_view/scr_company_view.gml
> +	            if (obj_ini.ship_location[obj_ini.veh_lid[company,i]]=="Lost") then bad=1;
may as well just place a continue in rather than having to evaluate bad later. Optional though as the gins are minimal

2023-10-10 11:54 UTC, GalacticChimp requested changes
Select All and Select Infantry dont work. Select Vehicles do work.

![select stuff](https://github.com/ZAB909/ChapterMaster/assets/63882831/35264de5-0a40-4d5e-90e1-fd767a57e4e6)

2023-10-10 12:00 UTC, OH296 commented
> Select All and Select Infantry dont work. Select Vehicles do work.
> 
> ![select stuff](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif) [ ![select stuff](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif) ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif) [ ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)

this is known and is not caused by this pr think it originates from one of the refactor files. I'm working on resolving this in a separate pr .

2023-10-10 12:07 UTC, GalacticChimp commented
> > Select All and Select Infantry dont work. Select Vehicles do work.
> > ![select stuff](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >       
> >         [
> >           
> >         
> >             ![select stuff](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >           ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >         
> >        [ ![select stuff](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif) ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >       
> >         [
> >           
> >         
> >             ![select stuff](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >           ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/63882831/273891156-35264de5-0a40-4d5e-90e1-fd767a57e4e6.gif)
> 
> this is known and is not caused by this pr think it originates from one of the refactor files. I'm working on resolving this in a separate pr .

ok, but the PR states it fixes this issue. The description + title have to be changed or a fix provided in this PR.

2023-10-10 12:26 UTC, OH296 commented
> > (snip)
> > this is known and is not caused by this pr think it originates from one of the refactor files. I'm working on resolving this in a separate pr .
> 
> ok, but this PR states it fixes this issue. The description + title have to be changed OR a fix provided in this PR.

the buttons never worked if you didn't have at least one unit selected first so the test you've posted will never do anything

2023-10-10 13:26 UTC, GalacticChimp approved these changes

2023-10-10 13:26 UTC, merged